---
# homebrew applications
applications:
  - ranger
  - autojump
  - git
  - tree
  - httpie
  - curl
  - wget
  - go
  - vim
  - fish
  - socat
  - watch
  - htop
  - jq
  - tree
  - httpie
  - coreutils
  - bash
  - socat

# homebrew cask applications
cask_applications:
  - google-chrome
  - docker
  - macvim
  - iterm2
  - vagrant
  - filezilla
